spring:
  application.name: blps
  config:
    import: optional:classpath:application-local.yml
    datasource:
      url: ${DB_URL:jdbc:h2:mem:fallbackdb}
      username: ${DB_USERNAME:sa}
      password: ${DB_PASSWORD:}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
camunda:
  client:
    mode: self-managed
    zeebe.gateway-address: localhost:26500
  operate:
    url: http://localhost:8080
    username: demo
    password: demo